env:
  browser: true
  es6: true
  node: true
  jest: true

extends:
  - google
  - next/core-web-vitals
  - plugin:tailwindcss/recommended

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - "@typescript-eslint"
  - react
  - unused-imports

rules:
  # Need to disable this for `unused-imports/no-unused-vars` to work properly
  no-unused-vars:
    - off

  # Need to disable this for `unused-imports/no-unused-vars` to work properly
  "@typescript-eslint/no-unused-vars":
    - off

  "unused-imports/no-unused-vars":
    - error
    - varsIgnorePattern: "^[_]+$"
      argsIgnorePattern: "^[_]+$"
      ignoreRestSiblings: true

  "unused-imports/no-unused-imports":
    - error

  # Need to disable this for `@typescript-eslint/indent` to work properly
  indent:
    - off

  "@typescript-eslint/indent":
    - error
    - 2
    - ignoredNodes:
        - TSTypeParameterInstantiation
      MemberExpression: 1

  linebreak-style:
    - error
    - unix

  max-len:
    - error
    - code: 119

  no-console:
    - error
    - allow:
      - warn
      - error

  # Need to disable this for `@typescript-eslint/no-restricted-imports` to work properly
  no-restricted-imports:
    - off

  "@typescript-eslint/no-restricted-imports":
    - error
    - patterns:
      - group:
          - .*
        message: Only absolute import, such as `@/const/auth` is allowed.

  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
      pathGroups:
        - pattern: react
          group: external
          position: before
      pathGroupsExcludedImportTypes:
        - react
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

  import/newline-after-import:
    - error
    - count: 2

  # Need to disable this for `@typescript-eslint/object-curly-spacing` to work properly
  object-curly-spacing: off

  "@typescript-eslint/object-curly-spacing":
    - error
    - never

  # Need to disable this for `@typescript-eslint/semi` to work properly
  semi:
    - off

  "@typescript-eslint/semi":
    - error

  space-in-parens:
    - error
    - never

  # Typescript will perform this check, no need for React to check it
  react/prop-types:
    - off

  react/jsx-tag-spacing:
    - error
    - beforeSelfClosing: never

  # Most of the dependencies are fine getting the initial value only
  react-hooks/exhaustive-deps:
    - off

  require-jsdoc:
    - off

  tailwindcss/classnames-order:
    - error

settings:
  react:
    version: detect
  tailwindcss:
    classRegex: "^class(.*)?$"
